spring:
  datasource:
    url: jdbc:postgresql://kubernetes.docker.internal:5432/student_crm
    username: student_crm_service
    password: student_crm_service
  kafka:
    bootstrap-servers: kafka:9092
    client-id: student-crm
